# PQC Self-Audit Workflow Template
# Copy to .github/workflows/pqc-audit.yml
name: PQC Self-Audit

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 3'  # Weekly on Wednesday 2 AM UTC
  workflow_dispatch:

jobs:
  self-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch full history for comprehensive audit
        fetch-depth: 0
        
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install PQC Audit Tool
      run: |
        pip install -e .
        
    - name: Run Self-Audit
      run: |
        pqc-audit scan . \
          --output-format json \
          --output-file pqc-audit-report.json \
          --severity-threshold medium \
          --include-dependencies
          
    - name: Generate Summary Report
      run: |
        pqc-audit report pqc-audit-report.json \
          --format markdown \
          --output pqc-summary.md
          
    - name: Upload Audit Results
      uses: actions/upload-artifact@v3
      with:
        name: pqc-audit-results
        path: |
          pqc-audit-report.json
          pqc-summary.md
          
    - name: Comment PR with Results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const summary = fs.readFileSync('pqc-summary.md', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## PQC Security Audit Results\n\n${summary}`
          });