# Security Scanning Workflow Template
# Copy to .github/workflows/security.yml
name: Security

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@v4
    - uses: github/codeql-action/init@v2
      with:
        languages: python
        queries: security-extended
    - uses: github/codeql-action/analyze@v2

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install security tools
      run: |
        pip install bandit[toml] safety semgrep
        
    - name: Run Bandit
      run: bandit -r src/ -f json -o bandit-report.json
      continue-on-error: true
      
    - name: Run Safety
      run: safety check --json --output safety-report.json
      continue-on-error: true
      
    - name: Run Semgrep
      run: semgrep --config=auto src/ --json -o semgrep-report.json
      continue-on-error: true
      
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: "*-report.json"