# Prometheus configuration for PQC Migration Audit monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'pqc-audit-monitor'
    environment: 'production'

# Rule files for alerting
rule_files:
  - "alert-rules.yml"
  - "recording-rules.yml"

# Scrape configurations
scrape_configs:
  # Application metrics
  - job_name: 'pqc-audit-app'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
    # Security-focused metric collection
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'pqc_audit_.*'
        target_label: __name__
        replacement: '${1}'

  # System metrics (node_exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s
    
  # Python application metrics
  - job_name: 'python-app'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    
    # Custom metrics for crypto scanning
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'python_.*|process_.*|pqc_.*'
        action: keep

  # Container metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8081']
    scrape_interval: 30s
    
  # Security scanner metrics
  - job_name: 'security-scanners'
    static_configs:
      - targets: ['localhost:9200']  # Custom security metrics endpoint
    scrape_interval: 60s
    
    # Filter for security-related metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'security_scan_.*|vulnerability_.*|compliance_.*'
        action: keep

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "localhost:9093"

# Remote write for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'pqc_audit_.*|security_.*'
#         action: keep