name: 🐛 Bug Report
description: Report a bug or unexpected behavior in PQC Migration Audit
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using the latest version of the tool
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Scan files in '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Actual behavior...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      placeholder: |
        - OS: [e.g., Ubuntu 20.04, macOS 12.0, Windows 11]
        - Python version: [e.g., 3.9.7]
        - Tool version: [e.g., 1.0.0]
        - Installation method: [e.g., pip, source]
      value: |
        - OS: 
        - Python version: 
        - Tool version: 
        - Installation method: 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please include relevant error logs or output
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: files
    attributes:
      label: Sample Files
      description: If applicable, provide sample files that trigger the bug (remove sensitive content)
      placeholder: Sample file content...
      render: text

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (cosmetic issue, workaround available)
        - Medium (functional issue with workaround)
        - High (functional issue without workaround)
        - Critical (security issue or data loss)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Additional context...