name: 🔒 Security Vulnerability Report
description: Report a security vulnerability (CONFIDENTIAL)
title: "[SECURITY] "
labels: ["security", "critical", "confidential"]
assignees: ["danieleschmidt"]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **SECURITY NOTICE**: This template is for reporting security vulnerabilities.
        
        If this is a **critical security issue**, please email security@terragonlabs.com directly instead of creating a public issue.
        
        For non-critical security improvements, you may use this template.

  - type: checkboxes
    id: severity_check
    attributes:
      label: Severity Assessment
      description: Please confirm the severity level
      options:
        - label: This is NOT a critical security vulnerability (safe to report publicly)
          required: true
        - label: I have NOT included sensitive information in this report
          required: true

  - type: dropdown
    id: vulnerability_type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Code injection
        - Cross-site scripting (XSS)
        - SQL injection
        - Authentication bypass
        - Authorization flaw
        - Cryptographic weakness
        - Information disclosure
        - Denial of service
        - Dependency vulnerability
        - Configuration issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue (avoid sensitive details)
      placeholder: High-level description of the vulnerability...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker achieve with this vulnerability?
      placeholder: Potential impact and attack scenarios...
    validations:
      required: true

  - type: dropdown
    id: cvss_score
    attributes:
      label: CVSS Score (if known)
      description: Common Vulnerability Scoring System score
      options:
        - "0.0 - None"
        - "0.1-3.9 - Low"
        - "4.0-6.9 - Medium"
        - "7.0-8.9 - High"
        - "9.0-10.0 - Critical"
        - "Unknown"

  - type: textarea
    id: affected_components
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      placeholder: |
        - File: src/example.py
        - Function: vulnerable_function()
        - Version: 1.0.0
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Proof of Concept
      description: Steps to reproduce (generalized, no exploits)
      placeholder: |
        1. Step 1
        2. Step 2
        3. Observe issue
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How do you suggest fixing this issue?
      placeholder: Suggested fixes or mitigations...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant CVE numbers, security advisories, or documentation
      placeholder: |
        - CVE-XXXX-XXXX
        - https://security-advisory.example.com

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Disclosure timeline preferences
      options:
        - label: I am willing to work with the maintainers on responsible disclosure
        - label: I would like to be credited in the security advisory (optional)
        - label: I understand this issue will be kept confidential until fixed

  - type: textarea
    id: contact
    attributes:
      label: Contact Information
      description: How can we reach you for follow-up? (optional)
      placeholder: Email or other secure contact method...